### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by nikonor** [artemeff/yam#1]
Я правильно понимаю, что функция авторизации не реализована?

**Comment by artemeff** [comment]
это вебвью до яндекс музыки с хоткеями, когда писалось — аутентификация была простой, в модальном окошке, сейчас она открывается в новом окне и это ее поломало. будет время — посмотрю

**Comment by nikonor** [comment]
спасибо!!

так я потому и искал что-то такое, чтобы с хоткейми нормальными.

**Comment by artemeff** [comment]
фиксанул, потыкал, в макоси все работает
https://github.com/artemeff/yam/releases/tag/0.2.0

**Comment by nikonor** [comment]
Спасибо!!
